joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50


knick_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Knick_Joint_1
    - Knick_Joint_2
    - Knick_Joint_3
    - Knick_Joint_4
    - Knick_Joint_5
    - Knick_Joint_6
    - Knick_Joint_7
  gains:
    Knick_Joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Knick_Joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Knick_Joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Knick_Joint_4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Knick_Joint_5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Knick_Joint_6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Knick_Joint_7:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
scara_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - Scara_Joint_1
    - Scara_Joint_2
    - Scara_Joint_3
  gains:
    Scara_Joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Scara_Joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Scara_Joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
